similar resources carousel
mitodl/mit-learn pull request #1835
Opened 2024-11-20 00:31 UTC by gumaerc

### What are the relevant tickets?
Closes https://github.com/mitodl/hq/issues/5878

### Description (What does it do?)

### Screenshots (if appropriate):

- [ ] Desktop screenshots
- [ ] Mobile width screenshots

### How can this be tested?

### Additional Context

2024-11-21 17:07 UTC, shanbady requested changes

2024-11-21 18:00 UTC, gumaerc commented on frontends/ol-components/src/components/LearningResourceExpanded/InfoSectionV2.tsx
> +  zIndex: -1,
I added this due to an issue with some elements of the drawer ending up "on top" of the sticky header in the drawer when you scroll down. I changed the approach here and instead set `zIndex: 1` on the header itself.

2024-11-21 18:02 UTC, gumaerc commented on frontends/ol-components/src/components/LearningResourceExpanded/InfoSectionV2.tsx
> +  zIndex: -1,
Here's an example I captured on RC of the icons from `InfoSection` flowing over onto the header:
![chrome_HBOmZykrsN](https://github.com/user-attachments/assets/38455561-587c-46ad-8820-619d553e677c)

2024-11-21 18:27 UTC, gumaerc commented
@shanbady This is ready for another look pending whatever @sovsey thinks we should do re: the empty space at the end of the carousel

2024-11-21 18:56 UTC, shanbady commented on frontends/ol-components/src/components/LearningResourceExpanded/InfoSectionV2.tsx
> +  zIndex: -1,
sounds good. just wanted to make sure it was something intentional and not left behind from previous testing.

2024-11-21 18:58 UTC, shanbady approved these changes
Looks good. Also worth mentioning @sovsey  the fix to resolve the performance issue on the vector results is up at https://github.com/mitodl/mit-learn/pull/1839 - if we have made a decision on the endpoint, we can use the vector based results once that pr is merged

2024-11-21 21:47 UTC, gumaerc commented
@sovsey I'm going to merge this. If we decide we want to even out the amount of cards in the carousels as @shanbady suggested, I can put up a separate PR for that.

2024-11-21 21:47 UTC, merged

2024-11-22 14:21 UTC, sovsey commented on frontends/api/src/test-utils/urls.ts
> +  ) => `${API_BASE_URL}/api/v1/learning_resources/${params.id}/vector_similar/`,
Let's update so it evenly pages.